CREATE DATABASE MASTERDUEL
USE MASTERDUEL

SELECT * FROM CARD
SELECT * FROM CARDPRODUCT
SELECT * FROM PRODUCT

SELECT * FROM CARD WHERE CATEGORY = "MONSTER" AND TYPE LIKE "%NORMAL"
SELECT * FROM CARD C INNER JOIN CARDMONSTER CD ON C.IDCARDCODE = CD.IDCARDCODE

SELECT C.IDCARDCODE, C.NAME, P.NAME, CAP.RARITY, CAP.INDIVIDUALPRICE
FROM CARD C INNER JOIN CARDPRODUCT CAP ON C.IDCARDCODE = CAP.IDCARDCODE INNER JOIN PRODUCT P ON P.IDPRODUCTCODE = CAP.IDPRODUCTCODE ORDER BY P.NAME

SELECT * FROM CARD WHERE Name LIKE '%%' OR Category LIKE '%%' OR Type LIKE '%%' OR Description LIKE '%%'

SELECT * FROM CARD WHERE IDCardCode = 31829185

SELECT P.NAME, P.PRICE, CAP.CARDRARITY, CAP.CARDINDPRICE FROM PRODUCT P INNER JOIN CARDPRODUCT CAP ON P.IDPRODUCTCODE = CAP.IDPRODUCTCODE WHERE CAP.IDCARDCODE = 31829185

SELECT * FROM CARD C INNER JOIN CARDMONSTER CM ON C.IDCARDCODE = CM.IDCARDCODE WHERE C.IDCARDCODE = 31829185

SELECT * FROM CARD WHERE IDCARDCODE = 05318639

SELECT * FROM CARD WHERE IDCARDCODE = 01546123 AND TYPE LIKE '%Fusion%'

SELECT * FROM PRODUCT WHERE IDPRODUCTCODE = 'BP01BRED'

SELECT C.IMG, C.NAME, CAP.CARDRARITY, CAP.CARDINDPRICE FROM CARD C INNER JOIN CARDPRODUCT CAP ON C.IDCARDCODE = CAP.IDCARDCODE INNER JOIN PRODUCT P ON CAP.IDPRODUCTCODE = P.IDPRODUCTCODE WHERE P.IDPRODUCTCODE = 'BP01BRED'